=== skltp-aggregerandetjanster/riv.crm.scheduling.GetAggregatedSubjectOfCareSchedule/GetAggregatedSubjectOfCareSchedule/src/main/resources/schemas/TD_SCHEDULING_1_1_0_R/interactions/GetAvailableDatesInteraction/GetAvailableDatesResponder_1.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. Inera AB licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:core="urn:riv:crm:scheduling:1" xmlns:tns="urn:riv:crm:scheduling:GetAvailableDatesResponder:1" xmlns:m1="urn:riv:crm:scheduling:GetAvailableDatesResponder:1.1" targetNamespace="urn:riv:crm:scheduling:GetAvailableDatesResponder:1" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.1">
<xs:annotation>
	<xs:documentation>
	  Beskrivning: Tjänsteschema för GetAvailableDatesResponder.
	  Revisioner: 
		2010-04-21: Release version 1.0 johan.eltes@callistaenterprise.se.
		2011-03-XX: Release version 1.1 johan.eltes@callistaenterprise.se.
			- Nytt, obligatoriskt request-element: subject_of_care
  </xs:documentation>
</xs:annotation>
  <xs:import namespace="urn:riv:crm:scheduling:1" schemaLocation="../../core_components/crm_scheduling_1.1.xsd" />
  <xs:import namespace="urn:riv:crm:scheduling:GetAvailableDatesResponder:1.1" schemaLocation="GetAvailableDatesResponder_1.1_ext.xsd" />
  <xs:element name="GetAvailableDates" type="tns:GetAvailableDatesType" />
  <xs:element name="GetAvailableDatesResponse" type="tns:GetAvailableDatesResponseType" />
  <xs:complexType name="GetAvailableDatesType">
    <xs:sequence>
      <xs:element name="healthcare_facility" type="core:HsaIdType" minOccurs="1" maxOccurs="1" />
      <xs:element name="bookingId" type="core:BookingIdType" minOccurs="0" maxOccurs="1" />
      <xs:element name="startDateInclusive" type="core:DT" minOccurs="1" maxOccurs="1" />
      <xs:element name="endDateInclusive" type="core:DT" maxOccurs="1" minOccurs="1" />
      <xs:element name="performer" type="core:HsaIdType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="timeTypeName" type="xs:string" minOccurs="0" maxOccurs="1" />
      <xs:element name="timeTypeID" type="core:TimeTypeIDType" minOccurs="0" maxOccurs="1" />
      <xs:element name="careTypeName" type="xs:string" minOccurs="0" maxOccurs="1" />
      <xs:element name="careTypeID" type="core:CareTypeIDType" minOccurs="0" maxOccurs="1" />
      <xs:element ref="m1:subject_of_care" minOccurs="1"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PerformerAvailabilityByDateType">
    <xs:sequence>
      <xs:element name="healthcare_facility" type="core:HsaIdType" minOccurs="1" maxOccurs="1" />
      <xs:element name="performer" type="core:HsaIdType" minOccurs="0" maxOccurs="1" />
      <xs:element name="date" type="core:DT" minOccurs="1" maxOccurs="1" />
      <xs:element name="resourceName" type="xs:string" minOccurs="0" maxOccurs="1" />
      <xs:element name="resourceID" type="core:ResourceIDType" minOccurs="0" maxOccurs="1" />
      <xs:element name="timeTypeName" type="xs:string" minOccurs="0" maxOccurs="1" />
      <xs:element name="timeTypeID" type="core:TimeTypeIDType" minOccurs="0" maxOccurs="1" />
      <xs:element name="careTypeName" type="xs:string" minOccurs="0" maxOccurs="1" />
      <xs:element name="careTypeID" type="core:CareTypeIDType" minOccurs="0" maxOccurs="1" />
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="GetAvailableDatesResponseType">
    <xs:sequence>
      <xs:element name="performerAvailabilityByDate" type="tns:PerformerAvailabilityByDateType" minOccurs="0" maxOccurs="unbounded" />
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== skltp-aggregerandetjanster/riv.crm.scheduling.GetAggregatedSubjectOfCareSchedule/GetAggregatedSubjectOfCareSchedule/src/main/resources/schemas/TD_SCHEDULING_1_1_0_R/interactions/GetAvailableDatesInteraction/GetAvailableDatesResponder_1.1_Response.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:GetAvailableDatesResponse xmlns:p="urn:riv:crm:scheduling:GetAvailableDatesResponder:1.1" xmlns:tns="urn:riv:crm:scheduling:GetAvailableDatesResponder:1" xmlns:tns1="urn:riv:crm:scheduling:1" xmlns:tns2="urn:riv:crm:scheduling:1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:riv:crm:scheduling:GetAvailableDatesResponder:1 GetAvailableDatesResponder_1.1.xsd ">
  <tns:performerAvailabilityByDate>
    <tns:healthcare_facility>tns:healthcare_facility</tns:healthcare_facility>
    <tns:performer>tns:performer</tns:performer>
    <tns:date>tns:date</tns:date>
    <tns:resourceName>tns:resourceName</tns:resourceName>
    <tns:resourceID>tns:resourceID</tns:resourceID>
    <tns:timeTypeName>tns:timeTypeName</tns:timeTypeName>
    <tns:timeTypeID>tns:timeTypeID</tns:timeTypeID>
    <tns:careTypeName>tns:careTypeName</tns:careTypeName>
    <tns:careTypeID>tns:careTypeID</tns:careTypeID>
  </tns:performerAvailabilityByDate>
</tns:GetAvailableDatesResponse>

=== skltp-aggregerandetjanster/riv.crm.scheduling.GetAggregatedSubjectOfCareSchedule/GetAggregatedSubjectOfCareSchedule/src/main/resources/schemas/TD_SCHEDULING_1_1_0_R/interactions/GetAvailableDatesInteraction/GetAvailableDatesResponder_1.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:GetAvailableDates xmlns:p="urn:riv:crm:scheduling:GetAvailableDatesResponder:1.1" xmlns:tns="urn:riv:crm:scheduling:GetAvailableDatesResponder:1" xmlns:tns1="urn:riv:crm:scheduling:1" xmlns:tns2="urn:riv:crm:scheduling:1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:riv:crm:scheduling:GetAvailableDatesResponder:1 GetAvailableDatesResponder_1.1.xsd ">
  <tns:healthcare_facility>tns:healthcare_facility</tns:healthcare_facility>
  <tns:bookingId>tns:bookingId</tns:bookingId>
  <tns:startDateInclusive>tns:startDateInclusive</tns:startDateInclusive>
  <tns:endDateInclusive>tns:endDateInclusive</tns:endDateInclusive>
  <tns:performer>tns:performer</tns:performer>
  <tns:timeTypeName>tns:timeTypeName</tns:timeTypeName>
  <tns:timeTypeID>tns:timeTypeID</tns:timeTypeID>
  <tns:careTypeName>tns:careTypeName</tns:careTypeName>
  <tns:careTypeID>tns:careTypeID</tns:careTypeID>
  <p:subject_of_care>p:subject_of_care</p:subject_of_care>
</tns:GetAvailableDates>
